//DEF_TYPE(name, index, type, place_in_union, print_format)
DEF_TYPE(NUM, 0, double, number, "%g")
DEF_TYPE(VAR, 1, char, var, "%c")
DEF_TYPE(OPER, 2, e_oper, var, NULL)
DEF_TYPE(KEYWORD, 3, int, var, NULL)
DEF_TYPE(NEXT, 4, int, var, NULL)
DEF_TYPE(FUNC, 5, int, var, NULL)
